### ISSUE TITLE
[Modify #8] Event Play 플로우 수정 필요

### ISSUE THREAD

**Issue by jayleefiction** [MungchiTheBlackThing/MungchiTheBlackThing#16]
- [ ] Event Play 플로우 문서화 정확하게 일치하지 않는 부분이 있어 작성해 둡니다!
시 아이콘이 떠 있을 때 = 맵 스크롤 가능 + 거미 및 파리 버튼 유지!
시 아이콘을 클릭하고 흰색 말풍선이 뜰 때 = 지금처럼 맵 스크롤 불가능 + 거미 및 파리 사라짐

아래 캡처한 문서 참고해 주세요.

<img width="301" alt="image" src="https://github.com/MungchiTheBlackThing/MungchiTheBlackThing/assets/151032205/e59088d9-79e3-4819-82fd-f1054ddbd16c">

**Comment by Invisible1nk** [comment]
수정 완료 했습니다
