### ISSUE TITLE
sleeping 수정

### ISSUE THREAD

**Issue by jayleefiction** [MungchiTheBlackThing/MungchiTheBlackThing#18]
<img width="722" alt="image" src="https://github.com/MungchiTheBlackThing/MungchiTheBlackThing/assets/151032205/e1af1b3b-814b-4f3b-9a29-071fcbbbab7b">

* sleeping phase일 때 스크롤이 현재 안 되고 메뉴 거미, 파리 체크리스트와 skip 버튼이 안 뜬다.

* sleep 중일 때 스크롤 정상적으로 가능해야 함
* 메뉴, 체크리스트 확인 가능해야 함
* 스킵 역시 가능해야 합니다.

**Comment by songsuyoung** [comment]
구현 완료
